### PR TITLE
issue 13 implementatio

### PR DESCRIPTION
**Pull request by YaroslavBoiko**
Modification of the class AssetClass according to user stories №13.

### CODE REVIEW

**Review by myroslavarm — COMMENTED** [review]
so this code is ok now but it doesn't really do anything in the application. you need to add your properties to the UI (see the example for activatable). before that please pull the changes that i added by simply executing `git pull` on the branch and you'll be up-to-date and won't have any merge problems.

**Comment by YaroslavBoiko** [comment]
okay, thx. Can you please tell me where is an example of activatable?

**Comment by YaroslavBoiko** [comment]
As I understood, it should be changed (supplemented) one of the classes in the airport-web-ui directory?

**Comment by YaroslavBoiko** [comment]
But wait a minute. As good as I remember, one participant of the Team Berlin yet implemented a user story num 13. So if he could implement this that it is not important to push this code one more time despite this fact that this code is ok. Moreover, if there are problems with the previous implementation, it will always be possible to replace it with this one.

**Pull request closed without merging**
